
### health check
GET https://13yn0uhl37.execute-api.ap-northeast-2.amazonaws.com/prod/health

### get stocks
GET https://13yn0uhl37.execute-api.ap-northeast-2.amazonaws.com/prod/stocks

### save stocks
POST https://13yn0uhl37.execute-api.ap-northeast-2.amazonaws.com/prod/stock

{
    "stockId": "10004",
    "stock": "쏘카",
    "brokers": ["미래에셋증권", "삼성증권", "유안타증권"]

}


### get stock
GET https://13yn0uhl37.execute-api.ap-northeast-2.amazonaws.com/prod/stock?stockId=10000


### delete
DELETE https://13yn0uhl37.execute-api.ap-northeast-2.amazonaws.com/prod/stock?stockId=10004


### patch
PATCH https://13yn0uhl37.execute-api.ap-northeast-2.amazonaws.com/prod/stock?